export const response = {
  responseId: '634f1dd3-0541-4b09-afaa-e601b0e93ea1',
  queryResult: {
    fulfillmentMessages: [
      {
        platform: 'PLATFORM_UNSPECIFIED',
        text: { text: ['This is a test response'] },
        message: 'text',
      },
    ],
    outputContexts: [],
    queryText: 'text',
    speechRecognitionConfidence: 0,
    action: 'input.unknown',
    parameters: { fields: {} },
    allRequiredParamsPresent: true,
    fulfillmentText: "I didn't get that. Can you say it again?",
    webhookSource: '',
    webhookPayload: null,
    intent: {
      inputContextNames: [],
      events: [],
      trainingPhrases: [],
      outputContexts: [],
      parameters: [],
      messages: [],
      defaultResponsePlatforms: [],
      followupIntentInfo: [],
      name:
        'projects/dhcs-demo-chat/agent/intents/de7ed62c-766a-4b48-9b91-0261ea59df5d',
      displayName: 'Default Fallback Intent',
      priority: 0,
      isFallback: true,
      webhookState: 'WEBHOOK_STATE_UNSPECIFIED',
      action: '',
      resetContexts: false,
      rootFollowupIntentName: '',
      parentFollowupIntentName: '',
      mlDisabled: false,
    },
    intentDetectionConfidence: 1,
    diagnosticInfo: null,
    languageCode: 'en-us',
  },
  webhookStatus: null,
}
