'use strict';

exports.__esModule = true;
var SET_TITLE = (exports.SET_TITLE = 'SET_TITLE');
var SET_AVATAR = (exports.SET_AVATAR = 'SET_AVATAR');
var SAVE_CLIENT = (exports.SAVE_CLIENT = 'SAVE_CLIENT');
var SAVE_RESPONSE = (exports.SAVE_RESPONSE = 'SAVE_RESPONSE');
var SAVE_USER_INPUT = (exports.SAVE_USER_INPUT = 'SAVE_USER_INPUT');
var SAVE_USER_RESPONSE = (exports.SAVE_USER_RESPONSE = 'SAVE_USER_RESPONSE');
var INITIATE_LOADING = (exports.INITIATE_LOADING = 'INITIATE_LOADING');
var UPDATE_TIME = (exports.UPDATE_TIME = 'UPDATE_TIME');
var TIMER_START = (exports.TIMER_START = 'TIMER_START');
var UPDATE_CURRENT_TIME = (exports.UPDATE_CURRENT_TIME = 'UPDATE_CURRENT_TIME');
var SHOW_BUTTON_BAR = (exports.SHOW_BUTTON_BAR = 'SHOW_BUTTON_BAR');
var HIDE_BUTTON_BAR = (exports.HIDE_BUTTON_BAR = 'HIDE_BUTTON_BAR');
var DISPLAY_ERROR = (exports.DISPLAY_ERROR = 'DISPLAY_ERROR');
var CLEAR_ERROR = (exports.CLEAR_ERROR = 'CLEAR_ERROR');
var CREATE_THEME = (exports.CREATE_THEME = 'CREATE_THEME');
var SHOW_WINDOW = (exports.SHOW_WINDOW = 'SHOW_WINDOW');
var HIDE_WINDOW = (exports.HIDE_WINDOW = 'HIDE_WINDOW');
var FULLSCREEN = (exports.FULLSCREEN = 'FULLSCREEN');
var WINDOWED = (exports.WINDOWED = 'WINDOWED');
var RECEIVE_WEBHOOK_DATA = (exports.RECEIVE_WEBHOOK_DATA =
  'RECEIVE_WEBHOOK_DATA');
